# Generated by Django 6.0 on 2025-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
