# Generated by Django 6.0 on 2025-12-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productsize_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
